### ISSUE TITLE
Update.php can't be run; Class 'DPL\DB\CreateTemplateUpdateMaintenance' not found

### ISSUE THREAD

**Issue by Facerafter** [Universal-Omega/DynamicPageList3#22]
Commit f138659873ddd43ec76f794376f91d63c30a58e7 seems to break update.php

When running update.php it encounters the following issue:
```
Cannot spawn child: DPL\DB\CreateTemplateUpdateMaintenance
[34275ca9772a6715de122a51] [no req]   Error from line 724 of /home/www-data/public_html/maintenance/includes/Maintenance.php: Class 'DPL\DB\CreateTemplateUpdateMaintenance' not found
Backtrace:
#0 /home/www-data/public_html/maintenance/update.php(184): Maintenance->runChild()
#1 /home/www-data/public_html/maintenance/doMaintenance.php(107): UpdateMediaWiki->execute()
#2 /home/www-data/public_html/maintenance/update.php(253): require_once(string)
#3 {main}
```
This is error is not present after I reverted to 169b2009942abcc849d930246199565d75df5d02

**Comment by Universal-Omega** [comment]
Fixed with a93d831
