### ISSUE TITLE
dpl 3.3.4 on mediawiki 1.35.2 throws exception

### ISSUE THREAD

**Issue by Tywyn** [Universal-Omega/DynamicPageList3#29]
Hi there,

tried to install dpl 3.3.4 on my 1.35.2 mediawiki, but when I enable the extension I get the following error in the error-log:

`[Mon Apr 26 10:34:08.132874 2021] [php7:error] [pid 1724] [client 192.168.1.6:43272] PHP Fatal error:  Uncaught Exception: Unable to open file /var/www/html/mediawiki-1.35.2-aquarien/extensions/DynamicPageList3/extension.json: filemtime(): stat failed for /var/www/html/mediawiki-1.35.2-aquarien/extensions/DynamicPageList3/extension.json in /var/www/html/mediawiki-1.35.2-aquarien/includes/registration/ExtensionRegistry.php:177\nStack trace:\n#0 /var/www/html/mediawiki-1.35.2-aquarien/includes/GlobalFunctions.php(51): ExtensionRegistry->queue()\n#1 /var/www/html/mediawiki-1.35.2-aquarien/LocalSettings.php(178): wfLoadExtension()\n#2 /var/www/html/mediawiki-1.35.2-aquarien/includes/Setup.php(143): require_once('/var/www/html/m...')\n#3 /var/www/html/mediawiki-1.35.2-aquarien/includes/WebStart.php(89): require_once('/var/www/html/m...')\n#4 /var/www/html/mediawiki-1.35.2-aquarien/index.php(44): require('/var/www/html/m...')\n#5 {main}\n  thrown in /var/www/html/mediawiki-1.35.2-aquarien/includes/registration/ExtensionRegistry.php on line 177`

Thank you for having a look at it.
Rainer

**Comment by Tywyn** [comment]
Ok, my fault. dpl was extracted to a folder DynamicPageList3-REL1_35 and not to DynamicPageList3.
Seems to work now...
