### ISSUE TITLE
Does not work with MW1.36 Release

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [Universal-Omega/DynamicPageList3#32]
Internal Error
```
[a69ed03a849443208178d5b9] /%E9%A6%96%E9%A1%B5 Error: Call to a member function getNsIndex() on null

Backtrace:

from /app/extensions/DynamicPageList3/includes/Parameters.php(629)
#0 [internal function]: DPL\Parameters->_namespace(string)
#1 /app/extensions/DynamicPageList3/includes/Parameters.php(79): call_user_func_array(array, array)
#2 /app/extensions/DynamicPageList3/includes/Parse.php(176): DPL\Parameters->__call(string, array)
#3 /app/extensions/DynamicPageList3/DynamicPageListHooks.php(300): DPL\Parse->parse(string, Parser, NULL, NULL, boolean)
#4 /app/includes/parser/Parser.php(3356): DynamicPageListHooks::dplParserFunction(Parser, string, string, string, string, string, string, string, string)
#5 /app/includes/parser/Parser.php(3041): Parser->callParserFunction(PPFrame_Hash, string, array)
#6 /app/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPFrame_Hash)
#7 /app/includes/parser/Parser.php(2879): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#8 /app/includes/parser/Parser.php(1549): Parser->replaceVariables(string)
#9 /app/includes/parser/Parser.php(639): Parser->internalParse(string)
#10 /app/includes/content/WikitextContent.php(375): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#11 /app/includes/content/AbstractContent.php(591): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#12 /app/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#13 /app/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#14 /app/includes/Revision/RevisionRenderer.php(217): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#15 /app/includes/Revision/RevisionRenderer.php(154): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#16 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#17 /app/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#18 /app/includes/poolcounter/PoolWorkArticleView.php(137): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#19 /app/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#20 /app/includes/page/ParserOutputAccess.php(281): PoolCounterWork->execute()
#21 /app/includes/page/Article.php(746): MediaWiki\Page\ParserOutputAccess->getParserOutput(WikiPage, ParserOptions, MediaWiki\Revision\RevisionStoreCacheRecord, integer)
#22 /app/includes/page/Article.php(561): Article->generateContentOutput(User, ParserOptions, integer, OutputPage, array)
#23 /app/includes/actions/ViewAction.php(74): Article->view()
#24 /app/includes/MediaWiki.php(531): ViewAction->show()
#25 /app/includes/MediaWiki.php(315): MediaWiki->performAction(Article, Title)
#26 /app/includes/MediaWiki.php(913): MediaWiki->performRequest()
#27 /app/includes/MediaWiki.php(546): MediaWiki->main()
#28 /app/index.php(53): MediaWiki->run()
#29 /app/index.php(46): wfIndexMain()
#30 {main}
```

**Comment by Universal-Omega** [comment]
Working on fixing.

**Comment by Universal-Omega** [comment]
This should now be fixed. Thank you for reporting!

**Comment by Aira-Sakuranomiya** [comment]
Still doesnt work
```
[602b971b22a0ae7512648374] /index.php?title=%E9%A6%96%E9%A1%B5&action=submit Error: Cannot access private property Parser::$mOutput

Backtrace:

from /app/extensions/DynamicPageList3/DynamicPageListHooks.php(527)
#0 /app/includes/HookContainer/HookContainer.php(338): DynamicPageListHooks::endReset(Parser, string)
#1 /app/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /app/includes/HookContainer/HookRunner.php(2910): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /app/includes/parser/Parser.php(1677): MediaWiki\HookContainer\HookRunner->onParserAfterTidy(Parser, string)
#4 /app/includes/parser/Parser.php(642): Parser->internalParseHalfParsed(string, boolean, boolean)
#5 /app/extensions/DynamicPageList3/includes/Parse.php(885): Parser->parse(string, Title, ParserOptions)
#6 /app/extensions/DynamicPageList3/includes/Parse.php(330): DPL\Parse->triggerEndResets(string, NULL, NULL, boolean)
#7 /app/extensions/DynamicPageList3/DynamicPageListHooks.php(300): DPL\Parse->parse(string, Parser, NULL, NULL, boolean)
#8 /app/includes/parser/Parser.php(3356): DynamicPageListHooks::dplParserFunction(Parser, string, string, string, string, string, string, string, string)
#9 /app/includes/parser/Parser.php(3041): Parser->callParserFunction(PPFrame_Hash, string, array)
#10 /app/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPFrame_Hash)
#11 /app/includes/parser/Parser.php(2879): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#12 /app/includes/parser/Parser.php(1549): Parser->replaceVariables(string)
#13 /app/includes/parser/Parser.php(639): Parser->internalParse(string)
#14 /app/includes/content/WikitextContent.php(375): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#15 /app/includes/content/AbstractContent.php(591): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#16 /app/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#17 /app/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#18 /app/includes/Revision/RevisionRenderer.php(217): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#19 /app/includes/Revision/RevisionRenderer.php(154): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#20 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#21 /app/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#22 /app/includes/Storage/DerivedPageDataUpdater.php(1347): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#23 [internal function]: MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#24 /app/includes/edit/PreparedEdit.php(104): call_user_func(array)
#25 /app/includes/edit/PreparedEdit.php(119): MediaWiki\Edit\PreparedEdit->getOutput()
#26 /app/includes/Storage/DerivedPageDataUpdater.php(1325): MediaWiki\Edit\PreparedEdit->__get(string)
#27 /app/includes/page/WikiPage.php(2326): MediaWiki\Storage\DerivedPageDataUpdater->getPreparedEdit()
#28 /app/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(34): WikiPage->prepareContentForEdit(WikitextContent)
#29 /app/includes/HookContainer/HookContainer.php(338): SpamBlacklistHooks::filterMergedContent(DerivativeContext, WikitextContent, Status, string, User, boolean)
#30 /app/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#31 /app/includes/HookContainer/HookRunner.php(1559): MediaWiki\HookContainer\HookContainer->run(string, array)
#32 /app/includes/editpage/Constraint/EditFilterMergedContentHookConstraint.php(90): MediaWiki\HookContainer\HookRunner->onEditFilterMergedContent(DerivativeContext, WikitextContent, Status, string, User, boolean)
#33 /app/includes/editpage/Constraint/EditConstraintRunner.php(88): MediaWiki\EditPage\Constraint\EditFilterMergedContentHookConstraint->checkConstraint()
#34 /app/includes/EditPage.php(2275): MediaWiki\EditPage\Constraint\EditConstraintRunner->checkConstraints()
#35 /app/includes/EditPage.php(1694): EditPage->internalAttemptSave(NULL, boolean)
#36 /app/includes/EditPage.php(669): EditPage->attemptSave(NULL)
#37 /app/includes/actions/EditAction.php(71): EditPage->edit()
#38 /app/includes/actions/SubmitAction.php(38): EditAction->show()
#39 /app/includes/MediaWiki.php(531): SubmitAction->show()
#40 /app/includes/MediaWiki.php(315): MediaWiki->performAction(Article, Title)
#41 /app/includes/MediaWiki.php(913): MediaWiki->performRequest()
#42 /app/includes/MediaWiki.php(546): MediaWiki->main()
#43 /app/index.php(53): MediaWiki->run()
#44 /app/index.php(46): wfIndexMain()
#45 {main}
```

**Comment by Universal-Omega** [comment]
Oh another error...

**Comment by Universal-Omega** [comment]
That issue is now fixed as well.
